- README.md
Really Tiny!
Just to update the planned date from the 1st of September, to the new date, 16th of September
> Update Planned Release Date

- challenge-style-guide.md
The old curriculum development gitter room has been replaced by contributors room.
> Update style guide with new contributors room.

- data-visualization/json/index.js
- data-visualization/json/index01.js
- data-visualization/json/index02.js
- data-visualization/json/index03.js
- data-visualization/json/index04.js
- data-visualization/json/index05.js
- data-visualization/json/index06.js
- data-visualization/json/index07.js
- data-visualization/json/index08.js
- data-visualization/json/index09.js
- data-visualization/json/index10.js
- data-visualization/json/index11.js
- data-visualization/json/index12.js
- data-visualization/json/index13.js
- data-visualization/json/index14.js
- data-visualization/json/index15.js
- data-visualization/json/index16.js
- data-visualization/json/index17.js
- data-visualization/json/index18.js
JSON challenges for issue #113 
Challenges are meant to address:
- valid JSON syntax
- stringifying an object to transfer over the web
- parsing a JSON string into the object it describes
- practice accessing values at various levels in an object, including looping over arrays within a JSON structure
Full code is saved in `index.js`.
Notes for reviewers - feedback is welcome on these!:
- Some of the challenges that explain concepts are a bit verbose - I think they still stay within the 2 minute rule, but if there are ways to trim them, suggestions welcome
- I have campers build the JSON object in a `.js` file (vs a `.json` file) so they can practice stringifying, parsing, and accessing it later in the lessons
- I'm rusty using JavaScript, let me know if you notice any conventions in the …
> feat: first draft of the JSON curriculum

- CONTRIBUTING.md
> Add Contributing Guidelines document

- learn-express-build-strock-trading-platform/server.js
- learn-express-build-strock-trading-platform/server010.js
- learn-express-build-strock-trading-platform/server015.js
- learn-express-build-strock-trading-platform/server020.js
- learn-express-build-strock-trading-platform/server030.js
- learn-express-build-strock-trading-platform/server040.js
- learn-express-build-strock-trading-platform/server050.js
- learn-express-build-strock-trading-platform/server060.js
- learn-express-build-strock-trading-platform/server070.js
- learn-express-build-strock-trading-platform/server080.js
- learn-express-build-strock-trading-platform/server090.js
- learn-express-build-strock-trading-platform/server100.js
- learn-express-build-strock-trading-platform/server110.js
- learn-express-build-strock-trading-platform/server120.js
- learn-express-build-strock-trading-platform/server130.js
- learn-express-build-strock-trading-platform/server140.js
- learn-express-build-strock-trading-platform/server150.js
- learn-express-build-strock-trading-platform/server160.js
- learn-express-build-strock-trading-platform/server170.js
- learn-express-build-strock-trading-platform/server180.js
- learn-express-build-strock-trading-platform/server190.js
- learn-express-build-strock-trading-platform/server200.js
first draft of stock trading platform instructions w/ Express.js
for issue #105
> feat: first draft of stock trading platform with express

- learn-css-grid-by-building-a-magazine/css/style.css
- learn-css-grid-by-building-a-magazine/index01.html
- learn-css-grid-by-building-a-magazine/index02.html
- learn-css-grid-by-building-a-magazine/index03.css
- learn-css-grid-by-building-a-magazine/index03.html
- learn-css-grid-by-building-a-magazine/index04.css
- learn-css-grid-by-building-a-magazine/index04.html
- learn-css-grid-by-building-a-magazine/index05.css
- learn-css-grid-by-building-a-magazine/index05.html
- learn-css-grid-by-building-a-magazine/index06.css
- learn-css-grid-by-building-a-magazine/index06.html
- learn-css-grid-by-building-a-magazine/index07.css
- learn-css-grid-by-building-a-magazine/index07.html
- learn-css-grid-by-building-a-magazine/index08.css
- learn-css-grid-by-building-a-magazine/index08.html
- learn-css-grid-by-building-a-magazine/index09.css
- learn-css-grid-by-building-a-magazine/index09.html
- learn-css-grid-by-building-a-magazine/index10.css
- learn-css-grid-by-building-a-magazine/index10.html
- learn-css-grid-by-building-a-magazine/index11.css
- learn-css-grid-by-building-a-magazine/index11.html
- learn-css-grid-by-building-a-magazine/index12.css
- learn-css-grid-by-building-a-magazine/index12.html
- learn-css-grid-by-building-a-magazine/index13.css
- learn-css-grid-by-building-a-magazine/index13.html
- learn-css-grid-by-building-a-magazine/index14.css
- learn-css-grid-by-building-a-magazine/index14.html
Related to the CSS Grid project
Closes #124
> feat: first draft of the CSS Grid Magazine lesson

- css-grid-magazine/TODO.md
Added TODO.md to CSS grid magazine project
> feat: Add To Do File to CSS Grid Magazine Project

- node-js-web-server/README.md
- node-js-web-server/index.js
- node-js-web-server/index000.js
- node-js-web-server/index010.js
- node-js-web-server/index020.js
- node-js-web-server/index030.js
- node-js-web-server/index040.js
- node-js-web-server/index050.js
- node-js-web-server/index060.js
- node-js-web-server/index070.js
- node-js-web-server/index080.js
- node-js-web-server/index090.js
- node-js-web-server/index100.js
- node-js-web-server/index101.js
- node-js-web-server/index102.js
- node-js-web-server/package.json
- node-js-web-server/public/about.html
- node-js-web-server/public/index.html
- node-js-web-server/public/products.html
This is the first draft of node js web server for fcc curriculum expansion
> First draft of node-js-web-server

- learn-regular-expressions-by-building-a-spam-filter/index.html
- learn-regular-expressions-by-building-a-spam-filter/makeDocs.js
- learn-regular-expressions-by-building-a-spam-filter/modelAnswer.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter010.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter020.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter030.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter040.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter050.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter060.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter070.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter080.js
- learn-regular-expressions-by-building-a-spam-filter/spamFilter090.js
- learn-regular-expressions-by-building-a-spam-filter/test.js
WIP. Corresponds to issue #122. Early feedback welcome, especially regarding the instructions (tone of voice, verbosity, how easy they are to follow, etc.)
> feat: first draft of Learn Regular Expressions by Building a Spam Filter

- css-grid-magazine/TODO.md
- express-strock-trading-platform/TODO.md
- node-js-web-server/TODO.md
- responsive-web-design-piano/TODO.md
Added or modified to do files for the CSS grid magazine, express stock trading, node web server, and responsive web piano projects.
> Added TODO.md files to several projects

- basic-javascript-role-playing-game/index840.js
- basic-javascript-role-playing-game/index845.js
- basic-javascript-role-playing-game/index850.js
- basic-javascript-role-playing-game/index855.js
- basic-javascript-role-playing-game/index860.js
- basic-javascript-role-playing-game/index865.js
- basic-javascript-role-playing-game/index870.js
- basic-javascript-role-playing-game/index875.js
- basic-javascript-role-playing-game/index880.js
- basic-javascript-role-playing-game/index885.js
- basic-javascript-role-playing-game/index890.js
- basic-javascript-role-playing-game/index895.js
- basic-javascript-role-playing-game/index900.js
Some files were missing at the end of the JavaScript project. I'm adding them back.
> fix: add missing js project files

- restful-api-grocery-list/server000.js
- restful-api-grocery-list/server005.js
- restful-api-grocery-list/server010.js
- restful-api-grocery-list/server015.js
- restful-api-grocery-list/server020.js
- restful-api-grocery-list/server025.js
- restful-api-grocery-list/server030.js
- restful-api-grocery-list/server035.js
- restful-api-grocery-list/server040.js
- restful-api-grocery-list/server045.js
- restful-api-grocery-list/server050.js
- restful-api-grocery-list/server055.js
- restful-api-grocery-list/server060.js
- restful-api-grocery-list/server065.js
- restful-api-grocery-list/server070.js
- restful-api-grocery-list/server075.js
Project and tests for Learn RESTful APIs by Building a Grocery List App #104
> Restful API project

- learn-CSS-by-Building-a-blog/blog39.html
- learn-CSS-by-Building-a-blog/blog40.html
- learn-CSS-by-Building-a-blog/blog41.html
- learn-CSS-by-Building-a-blog/blog42.html
- learn-CSS-by-Building-a-blog/blog43.html
Started with the first steps for the blog page HTML file.
> feat: steps for the blog file

- learn-css-grid-by-building-a-magazine/css/style000.css
- learn-css-grid-by-building-a-magazine/css/style010.css
- learn-css-grid-by-building-a-magazine/css/style020.css
- learn-css-grid-by-building-a-magazine/css/style030.css
- learn-css-grid-by-building-a-magazine/css/style040.css
- learn-css-grid-by-building-a-magazine/css/style050.css
- learn-css-grid-by-building-a-magazine/css/style060.css
- learn-css-grid-by-building-a-magazine/css/style070.css
- learn-css-grid-by-building-a-magazine/css/style080.css
- learn-css-grid-by-building-a-magazine/css/style090.css
- learn-css-grid-by-building-a-magazine/css/style100.css
- learn-css-grid-by-building-a-magazine/css/style110.css
- learn-css-grid-by-building-a-magazine/css/style120.css
- learn-css-grid-by-building-a-magazine/css/style130.css
- learn-css-grid-by-building-a-magazine/css/style140.css
- learn-css-grid-by-building-a-magazine/css/style150.css
- learn-css-grid-by-building-a-magazine/css/style160.css
- learn-css-grid-by-building-a-magazine/css/style170.css
- learn-css-grid-by-building-a-magazine/css/style180.css
- learn-css-grid-by-building-a-magazine/css/style190.css
- learn-css-grid-by-building-a-magazine/css/style200.css
- learn-css-grid-by-building-a-magazine/css/style210.css
- learn-css-grid-by-building-a-magazine/css/style220.css
- learn-css-grid-by-building-a-magazine/css/style230.css
- learn-css-grid-by-building-a-magazine/css/style240.css
- learn-css-grid-by-building-a-magazine/css/style250.css
- learn-css-grid-by-building-a-magazine/index.html
- learn-css-grid-by-building-a-magazine/styles.css
Initial code for learn-css-grid-by-building-a-magazine.
> feat-learn-css-grid

- d3-dashboard/105.js
Adds a missing word to a `d3-dashboard` step.
> fix: add a missing word

- learn-data-structures-by-building-a-shopping-cart/.prettierrc
- learn-data-structures-by-building-a-shopping-cart/index03.js
- learn-data-structures-by-building-a-shopping-cart/index04.js
- learn-data-structures-by-building-a-shopping-cart/index05.js
- learn-data-structures-by-building-a-shopping-cart/index06.js
- learn-data-structures-by-building-a-shopping-cart/index07.js
- learn-data-structures-by-building-a-shopping-cart/index08.js
- learn-data-structures-by-building-a-shopping-cart/index08a.js
- learn-data-structures-by-building-a-shopping-cart/index08b.js
This is an initial draft to demonstrate how we can introduce OOP organically in the shopping cart project.
As per our call @scissorsneedfoodtoo, kindly review and comment if you think I should proceed further in this manner or if the approach needs adjustment.
Thanks
Links #120
> initial draft

- learn-data-structures-by-building-a-shopping-cart/index10.js
- learn-data-structures-by-building-a-shopping-cart/index10a.js
- learn-data-structures-by-building-a-shopping-cart/index10b.js
- learn-data-structures-by-building-a-shopping-cart/index10c.js
- learn-data-structures-by-building-a-shopping-cart/index10d.js
- learn-data-structures-by-building-a-shopping-cart/index10e.js
- learn-data-structures-by-building-a-shopping-cart/index11a.js
- learn-data-structures-by-building-a-shopping-cart/index11b.js
This PR builds on the previous modifications.
I have touched on how an existing object can be reused and highlighted the trivial copy-paste method. This organically moves on towards introducing the idea of using functions to build objects to make code reusable and maintainable.
In the end, I have highlighted the problem of using the object generator function which forced me to give a rough idea of what memory is.
I have tried to keep it as digestible as I could but I understand that this may require several iterations.
@scissorsneedfoodtoo would love to hear your thoughts.
> introducing concepts of object generators + working to Object.create

- intermediate-algorithm-scripting-yahtzee-game/css/style.css
- intermediate-algorithm-scripting-yahtzee-game/index.html
- intermediate-algorithm-scripting-yahtzee-game/js/index.js
I and @perezvon have created a simpler version of the Yahtzee dice game. The game is running live on: https://perezvon.github.io/fcc-dice-game/
I hope you will like it @scissorsneedfoodtoo. Your feedback will be very helpful to us. Also please tell us the areas we need to improve on. 
I'll work on the challenge descriptions after some time as I'm busy with some other work right now so if you think this looks good enough then we should merge it.  
🥂
> feat: Intermediate algorithm scripting Yahtzee game

- learn-css-grid-by-building-a-magazine/index.html
Checklist:
Closes #XXXXX
I may or may not have filched the text from [Quincy's original announcement](https://forum.freecodecamp.org/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) but thought it would be cool to have the campers write a "real" article instead of placeholder text.
> feat: use real text

- css-penguin/index.html
- css-penguin/styles.css
Checklist:
Closes #XXXXX
For our second-to-last project!
> feat: penguin draft

- css-balance-sheet/index.html
- css-balance-sheet/styles.css
Checklist:
Closes #XXXXX
Prototype ready for review!
> feat: balance sheet

- css-color-markers/index.html
- css-color-markers/styles.css
> feat: add css color markers project

- decimal-to-binary/index.html
- decimal-to-binary/index.js
- decimal-to-binary/styles.css
This project is meant to teach recursion.
I added in an animation to show the call stack. 
If the user enters the number 5, then the animation will trigger. Otherwise it will just show the binary result. 
Link to live project: https://r886f.csb.app/
Checklist:
> feat: adding decimal to binary project to new JS curriculum 

- learn-array-methods-by-building-a-statistics-calculator/index.html
- learn-array-methods-by-building-a-statistics-calculator/script.js
- learn-array-methods-by-building-a-statistics-calculator/styles.css
Checklist:
Closes #XXXXX
Small project to teach array methods before diving in to the functional programming spreadsheet
> feat: stat calculator

- README.md
I updated the readme to reflect the current use for this repo.
Checklist:
> docs: updating readme to remove details on contributing project prototypes

- javascript-algorithms-and-data-structures/learn-the-date-object-by-building-a-date-formatter/index.html
- javascript-algorithms-and-data-structures/learn-the-date-object-by-building-a-date-formatter/script.js
- javascript-algorithms-and-data-structures/learn-the-date-object-by-building-a-date-formatter/styles.css
This will be the 4th project in the new curriculum. 
This is a short project that will go after the music player and introduce campers to the date object. It also teaches the reverse and join methods which are needed for the 1st certification project. 
https://w77dft.csb.app/
Checklist:
> feat: adding date formatter project

- javascript-algorithms-and-data-structures/Learn-Intermediate-OOP-by-Building-a-Platformer-Game/index.html
- javascript-algorithms-and-data-structures/Learn-Intermediate-OOP-by-Building-a-Platformer-Game/script.js
- javascript-algorithms-and-data-structures/Learn-Intermediate-OOP-by-Building-a-Platformer-Game/styles.css
https://u57qxn.csb.app/
https://codesandbox.io/s/fcc-platformer-u57qxn?file=/index.html:0-881
Checklist:
> feat: adding Learn Intermediate OOP by Building a Platformer Game

- responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/index.html
- responsive-web-design/learn-intermediate-css-by-building-a-cat-painting/styles.css
> feat: add cat painting intermediate CSS project

- javascript-algorithms-and-data-structures/learn-basic-string-and-array-methods-by-building-a-music-player-app/script.js
- javascript-algorithms-and-data-structures/learn-basic-string-and-array-methods-by-building-a-music-player-app/styles.css
Checklist:
Closes #XXXXX
Technically, you are not supposed to nest `p` and `div` elements inside of a `button`, so I have switched them all to `span`s or removed them completely. I also put `aria-current` on the list item itself (which probably makes more sense). Now we have better semantics and cleaner HTML.
> fix(a11y): improve playlist semantics

- javascript-algorithms-and-data-structures/learn-debugging-by-building-a-TODO-app/index.html
- javascript-algorithms-and-data-structures/learn-debugging-by-building-a-TODO-app/script.js
- javascript-algorithms-and-data-structures/learn-debugging-by-building-a-TODO-app/styles.css
Checklist:
Closes #XXXXX
These updates are based on a recent discussion with Oliver, and should hopefully make it more clear which elements learners are working with while writing JS. I also added a bit of responsiveness as well, and tried to simplify the structure and styling as much as possible.
Also, it adds some code to close the dialog modal with the `.close()` method based on Jessica's suggestion. This should help us get around some platform limitations.
More context here: https://chat.freecodecamp.org/group/front-3-2023?msg=vkafmcPdmbadnDM39
> fix: suggested changes for todo app

- javascript-algorithms-and-data-structures/learn-basic-string-and-array-methods-by-building-a-music-player-app/script.js
- javascript-algorithms-and-data-structures/learn-basic-string-and-array-methods-by-building-a-music-player-app/styles.css
Checklist:
This PR adds a couple of important improvements like playing the next song after the current one is finished. Also, reseting the player state and HTML attributes for accessibility in certain states (the final song finishes playing, songs are shuffled, and so on).
Other changes include reordering the order of the functions, renaming functions for clarity (`playNextSong` rather than `nextSong`), and using numbers for song ids instead of strings to simplify the code a bit.
It also adds some comments that may help while breaking the project down into steps.
> fix: music player improvements

- scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/vigenere.py
Checklist:
Closes #XXXXX
Adding a new project to the Python curriculum
> feat(curriculum): add Vigenère cipher project

- scientific-computing-with-python/learn-data-structures-by-building-the-shortest-path-algorithm/shortest-path-algorithm.py
Checklist:
Closes #XXXXX
Adding a new project to the Python curriculum.
Note: when different paths of the same length are available, only the first one found is considered. If I'm not wrong it should be always the one with less number of nodes.
> feat(curriculum): add shortest path algorithm project

- scientific-computing-with-python/learn-tree-traversal-by-building-a-binary-search-tree/binary-search-tree.py
Checklist:
Closes #XXXXX
Adding a new project to the Python curriculum.
> feat(curriculum): add binary search tree

- scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/sudoku_solver.py
Checklist:
Closes #XXXXX
Adding a new project to the Python curriculum
> feat(curriculum): add sudoku solver project

- scientific-computing-with-python/learn-regular-expressions-by-building-a-password-generator/password_generator.py
Checklist:
Closes #XXXXX
Adding a new project the Python curriculum.
> feat(curriculum): add password generator project

- scientific-computing-with-python/learn-lambda-functions-by-building-a-expense-tracker/expense-tracker.py
Checklist:
Closes #XXXXX
Added the expense tracker project
> Add expense tracker project

- scientific-computing-with-python/learn-list-comprehension-by-building-a-case-converter/caseconverter.py
Checklist:
Added a new project to the Python curriculum.
> feat(curriculum): added case converter project with list comprehension

- scientific-computing-with-python/learn-numerical-analysis-by-finding-the-square-root-of-a-number-using-the-bisection-method/bisection-method.py
Checklist:
Closes #XXXXX
Add the prototype to teach  numerical analysis by finding the square root of a number using the bisection method.
> feat: add bisection method project Python curriculum

- javascript-algorithms-and-data-structures/learn-basic-javascript-by-building-a-pyramid-generator/script.js
Checklist:
Closes #XXXXX
This one is a LOT of comments. The application itself is simple, but there's a lot of redoing things with different approaches to teach different concepts and syntax. I probably forgot to note a bunch of it, but if we're happy with just the overall final result I'll start breaking it into steps.
> feat: prototype pyramid generator

- scientific-computing-with-python/learn-special-methods-by-building-a-vector-space/vectors.py
Checklist:
A possible project to add to the Python curriculum.
> feat: add vector space prototype

- javascript-algorithms-and-data-structures/review-js-fundamentals-by-building-a-gradebook-app/script.js
This is PR is to add the first JS review project that will go between the pyramid project and RPG project.
It corresponds with this PR here 
https://github.com/freeCodeCamp/freeCodeCamp/pull/54489
Checklist:
Closes #XXXXX
> feat: adding 1st JS review project

- scientific-computing-with-python/learn-special-methods-by-building-a-vector-space/vectors.py
Checklist:
Closes #XXXXX
Following the suggestions on [#54140](https://github.com/freeCodeCamp/freeCodeCamp/pull/54140):
- `__dict__` has been substituted with `vars()`
- `__getattribute__()` has been substituted with `getattr()`
- the condition of several `if` statements that were using `isinstance` has been replaced because it wasn't preventing from performing operations between `R2Vector` and `R3Vector` instances.
> fix: vector space prototype

- scientific-computing-with-python/learn-encapsulation-by-drawing-a-projectile-trajectory/projectile-trajectory.py
I am creating a PR so I can share the prototype
how to test: execute the py file in the terminal, it will have an interactive menu
>  Learn Encapsulation by Drawing a Projectile Trajectory

- frontend-cert/html-projects/cat-photo-app/index.html
The only thing I have changed about this project was to remove the form section.
Forms have their own module in the frontend cert and there will be a separate project to go into forms in more detail. 
Checklist:
Closes #378
> chore: adding revised cat photo app workshop to frontend cert

- frontend-cert/html-projects/student-exams-table/index.html
> chore: adding student table workshop

- frontend-cert/html-projects/hotel-feedback-form/index.html
> chore: adding hotel feedback form workshop

- frontend-cert/html-projects/blog-page/index.html
This will be workshop(step based tutorial) used to teach semantic HTML in depth.
Checklist:
Closes #383
> chore: adding blog page workshop

- frontend-cert/js-projects/greeting-bot/script.js
This workshop will be JavaScript only and teach the following:
- let
- const
- assignment
- reassignment
- basic string usage
- console.log
- camelCase
These project was designed to only teach a handful of new concepts and be a shorter project.
In the current JS beta curriculum, campers have serious holes in their fundamentals.
So the fix will be to have many more shorter workshops and labs, especially in the beginning, so they can grasp the fundamentals better
Checklist:
Closes #410
> chore: adding 1st JS only workshop

- frontend-cert/js-projects/js-teaching-bot/script.js
This will be the intro strings workshop at the beginning of the the JavaScript strings module.
It covers the following:
- const
- assignment
- string concatenation using the + operator
- template literals
- str.length property
- bracket notation and retrieving characters from strings
- str.indexOf method
Checklist:
Closes #414
> chore: adding intro strings workshop

- frontend-cert/js-projects/guessing-game/script.js
This workshop will be the campers introduction into working with the Math object.
They will also be introduced to if/else statements and equality operator.
But the next module will go deeper into conditionals, booleans and equality 
Checklist:
Closes #417
> chore: adding guessing game workshop to frontend cert

- frontend-cert/html-projects/chocolate-cookies-recipe/index.html
- frontend-cert/html-projects/chocolate-cookies-recipe/user-stories.md
Since we are hoping to have all the prototypes as a live demo users can click on, I thought this one could use some improvements. You can see it in action here: https://mot01.github.io/html-lab-1/
Really, I was creating a PR to the main repo to add this lab and wanted to include the link, so I gave it some improvements.
Also, I couldn't help myself - I changed the user stories slightly so users can create any recipe they want instead of the cookies. We can revert that if we want.
Checklist:
Closes #XXXXX
> fix: improve cookie recipe prototype

- frontend-cert/js-projects/story-teller-app/index.html
- frontend-cert/js-projects/story-teller-app/script.js
- frontend-cert/js-projects/story-teller-app/styles.css
> chore: add DOM and events workshop

- frontend-cert/css-projects/book-inventory/index.html
- frontend-cert/css-projects/book-inventory/styles.css
- frontend-cert/css-projects/book-inventory/user-stories.md
Checklist:
Closes #400 
In this case I would provide an example page to show how the final result should look like.
> feat: add css attribute selectors lab prototype

- frontend-cert/js-projects/music-instrument-filter/index.html
- frontend-cert/js-projects/music-instrument-filter/script.js
- frontend-cert/js-projects/music-instrument-filter/styles.css
This is a small workshop to have campers practice working with change events and adding HTML using `innerHTML`
Checklist:
Closes #451
> chore: add music filter change event workshop

- frontend-cert/js-projects/student-grade-tracker/script.js
> feat: added objects workshop project

- frontend-cert/css-projects/css-colors/index.html
- frontend-cert/css-projects/css-colors/styles.css
- frontend-cert/css-projects/css-colors/user-stories.md
> feat: add css colors lab

- frontend-cert/html-projects/travel-agency-page/index.html
- frontend-cert/html-projects/travel-agency-page/user-stories.md
> fix: improve travel page

- javascript-algorithms-and-data-structures/learn-callbacks-by-building-a-testing-lib/script.js
Checklist:
Closes #XXXXX
This is a prototype  of what I think I am trying to build for the PR in https://github.com/freeCodeCamp/freeCodeCamp/pull/55283. A prototype might help make sure I am on the right track.
> feat: create callback project prototype

- frontend-cert/js-projects/hash-table/script.js
- frontend-cert/js-projects/hash-table/user-stories.md
Checklist:
Closes #472 
Changes respect to the  original code:
- replaced `var` with `let` and `const`
- converted the function + constructor into a class
The class has a static method `hash`, but I'm not sure if campers know about static methods at this point. If not this can be  turned back into a function defined outside the class.
User stories may have to more more detailed, depending on how much has been already taught about hash tables.
> chore: covert hash table challenge into lab

- frontend-cert/js-projects/stack-class/script.js
- frontend-cert/js-projects/stack-class/user-stories.md
> chore: covert stack class challenge into lab

- frontend-cert/js-projects/quicksort/script.js
- frontend-cert/js-projects/quicksort/user-stories.md
> chore: convert quicksort challenge into lab

- frontend-cert/css-projects/confidential-email/index.html
- frontend-cert/css-projects/confidential-email/styles.css
- frontend-cert/css-projects/confidential-email/user-stories.md
Checklist:
Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/397
> feat: add confidential email lab

- frontend-cert/css-projects/newspaper-article/index.html
- frontend-cert/css-projects/newspaper-article/styles.css
- frontend-cert/css-projects/newspaper-article/user-stories.md
> feat: add typography lab prototype

- frontend-cert/css-projects/poker-hand/index.html
- frontend-cert/css-projects/poker-hand/styles.css
- frontend-cert/css-projects/poker-hand/user-stories.md
Checklist:
Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/398
> feat: add flexbox lab (poker hand)

- frontend-cert/js-projects/js-only-calculator/script.js
> chore: adding functions workshop

- frontend-cert/css-projects/todo-list-stylized/index.html
- frontend-cert/css-projects/todo-list-stylized/styles.css
- frontend-cert/css-projects/todo-list-stylized/user-stories.md
> chore: add to-do list prototype 

- frontend-cert/js-projects/linked-lists/script.js
- frontend-cert/js-projects/linked-lists/user-stories.md
> chore: convert linked list challenges into lab

- scientific-computing-with-python/learn-inheritance-by-building-an-equation-solver/quadratic_equation_solver.py
- scientific-computing-with-python/learn-interfaces-by-building-an-equation-solver/quadratic_equation_solver.py
Checklist:
A possible project to add to the new Python curriculum.
> feat: add equation solver prototype

- frontend-cert/js-projects/sentence-analyzer/script.js
> feat: adding sentence analyzer loops project

- frontend-cert/js-projects/shopping-list/script.js
> feat: add shopping list arrays workshop

- frontend-cert/js-projects/library-manager/script.js
> feat: add-library-manager-hoc-project

- frontend-cert/html-projects/survey-form/index.html
- frontend-cert/html-projects/survey-form/user-stories.md
> chore: converted survey form project into lab

- frontend-cert/js-projects/functions/script.js
- frontend-cert/js-projects/functions/user-stories.md
> feat: add functions lab

- frontend-cert/js-projects/lab-realtime-character-counter/index.html
- frontend-cert/js-projects/lab-realtime-character-counter/script.js
- frontend-cert/js-projects/lab-realtime-character-counter/styles.css
- frontend-cert/js-projects/lab-realtime-character-counter/user-stories.md
> feat: add Real-Time Counter Lab

- frontend-cert/js-projects/lab-favourite-toggler/index.html
- frontend-cert/js-projects/lab-favourite-toggler/script.js
- frontend-cert/js-projects/lab-favourite-toggler/styles.css
- frontend-cert/js-projects/lab-favourite-toggler/user-stories.md
> feat: add favourite icon toggler lab

- frontend-cert/js-projects/lab-factorial/script.js
- frontend-cert/js-projects/lab-factorial/user-stories.md
> feat: add factorial lab

- frontend-cert/js-projects/fortune-teller-app/script.js
- frontend-cert/js-projects/fortune-teller-app/user-stories.md
> feat: add fortune teller lab

- frontend-cert/js-projects/nth-fibonacci-number/script.js
- frontend-cert/js-projects/nth-fibonacci-number/user-stories.md
> chore: add n-th Fibonacci number lab

- frontend-cert/js-projects/second-functions/script.js
- frontend-cert/js-projects/second-functions/user-stories.md
> feat: add second functions lab

- frontend-cert/js-projects/js-lunch-picker/script.js
- frontend-cert/js-projects/js-lunch-picker/user-stories.md
> feat: add lunch picker lab (JS only)

- frontend-cert/js-projects/depth-first-search/script.js
- frontend-cert/js-projects/depth-first-search/user-stories.md
> chore: converted depth- first search challenge into lab

- frontend-cert/js-projects/quiz-game/script.js
- frontend-cert/js-projects/quiz-game/user-stories.md
> feat: add object lab (JS only)

- frontend-cert/html-projects/lab-landing-page/index.html
- frontend-cert/html-projects/lab-landing-page/styles.css
- frontend-cert/html-projects/lab-landing-page/user-stories.md
> feat: convert product landing page to lab

- frontend-cert/js-projects/lab-pokemon/index.html
- frontend-cert/js-projects/lab-pokemon/script.js
- frontend-cert/js-projects/lab-pokemon/styles.css
- frontend-cert/js-projects/lab-pokemon/user-stories.md
> feat: convert pokemon search app to lab

- frontend-cert/js-projects/cash-register/script.js
- frontend-cert/js-projects/cash-register/user-stories.md
> chore: covert cash register into lab

- frontend-cert/css-projects/styling-forms/index.html
- frontend-cert/css-projects/styling-forms/styles.css
- frontend-cert/css-projects/styling-forms/user-stories.md
> feat: add styling forms lab 

- frontend-cert/html-projects/lab-personal-portfolio/index.html
- frontend-cert/html-projects/lab-personal-portfolio/styles.css
- frontend-cert/html-projects/lab-personal-portfolio/user-stories.md
> feat: convert personal portfolio to lab

- frontend-cert/css-projects/technical-document/index.html
- frontend-cert/css-projects/technical-document/styles.css
- frontend-cert/css-projects/technical-document/user-stories.md
> feat: convert technical document project to lab

- frontend-cert/html-projects/faq-page/index.html
- frontend-cert/html-projects/faq-page/user-stories.md
> FAQ page for second semantic lab

- frontend-cert/js-projects/js-chat-bot/script.js
- frontend-cert/js-projects/js-chat-bot/user-stories.md
> chore: add lab for chat bot(JS only)

- frontend-cert/js-projects/regex-sandbox/index.html
- frontend-cert/js-projects/regex-sandbox/script.js
- frontend-cert/js-projects/regex-sandbox/styles.css
- frontend-cert/js-projects/regex-sandbox/user-stories.md
> feat: add regex lab

- frontend-cert/js-projects/bookmark-manager/index.html
- frontend-cert/js-projects/bookmark-manager/script.js
- frontend-cert/js-projects/bookmark-manager/styles.css
- frontend-cert/js-projects/bookmark-manager/user-stories.md
> feat: add bookmark manager lab (localStorage lab)

- frontend-cert/js-projects/weather-app/index.html
- frontend-cert/js-projects/weather-app/script.js
- frontend-cert/js-projects/weather-app/styles.css
- frontend-cert/js-projects/weather-app/user-stories.md
> chore: added lab for weather app to review fetch API in frontend cert

- frontend-cert/css-projects/pseudo-classes-lab/index.html
- frontend-cert/css-projects/pseudo-classes-lab/styles.css
- frontend-cert/css-projects/pseudo-classes-lab/user-stories.md
> chore add pseudo classes lab

- frontend-cert/react-projects/resuable-profile-component/index.html
- frontend-cert/react-projects/resuable-profile-component/styles.css
> feat: add reusable card component workshop

- frontend-cert/js-projects/recipe-converter/index.html
- frontend-cert/js-projects/recipe-converter/script.js
- frontend-cert/js-projects/recipe-converter/styles.css
> feat: add functional programming workshop (recipe ingredient converter)

- frontend-cert/js-projects/library-manager/script.js
Checklist:
Closes #XXXXX
This PR updates the library manager workshop to use functions so it can be more testable.
> fix: updated library manager to use functions

- frontend-cert/js-projects/functional-programming-lab/index.html
- frontend-cert/js-projects/functional-programming-lab/script.js
- frontend-cert/js-projects/functional-programming-lab/styles.css
- frontend-cert/js-projects/functional-programming-lab/user-stories.md
> feat: functional programming lab

- frontend-cert/react-projects/reusable-footer/index.html
- frontend-cert/react-projects/reusable-footer/styles.css
- frontend-cert/react-projects/reusable-footer/user-stories.md
> feat: add reusable footer React

- frontend-cert/react-projects/react-use-state/index.html
- frontend-cert/react-projects/react-use-state/styles.css
- frontend-cert/react-projects/react-use-state/user-stories.md
> feat: add React useState lab

- frontend-cert/js-projects/forum-leaderboard/index.html
- frontend-cert/js-projects/forum-leaderboard/script.js
- frontend-cert/js-projects/forum-leaderboard/styles.css
- frontend-cert/js-projects/forum-leaderboard/user-stories.md
Checklist:
Closes #638 
The seed for this lab should include the entire HTML and CSS and the following JS:
```js
const forumLatest = "https://cdn.freecodecamp.org/curriculum/forum-latest/latest.json";
const forumTopicUrl = "https://forum.freecodecamp.org/t/";
const forumCategoryUrl = "https://forum.freecodecamp.org/c/";
const avatarUrl = "https://sea1.discourse-cdn.com/freecodecamp";
const allCategories = {
299: { category: "Career Advice", className: "career" },
409: { category: "Project Feedback", className: "feedback" },
417: { category: "freeCodeCamp Support", className: "support" },
421: { category: "JavaScript", className: "javascript" },
423: { category: "HTML - CSS", className: "html-css" },
424: { category: "Python", className: "python" },
432: { category: "You Can Do This!", …
```
> chore: forum leaderboard lab

- frontend-cert/js-projects/voting-system/index.js
- frontend-cert/js-projects/voting-system/user-stories.md
> feat: add Map and Set lab prototype

- fullstack-cert/js-projects/drum-machine/index.html
- fullstack-cert/js-projects/drum-machine/script.js
- fullstack-cert/js-projects/drum-machine/styles.css
- fullstack-cert/js-projects/drum-machine/user-stories.md
> Added drum machine prototype

- fullstack-cert/react-projects/toggle-visibility/index.html
- fullstack-cert/react-projects/toggle-visibility/index.jsx
- fullstack-cert/react-projects/toggle-visibility/styles.css
> feat: add React useState Hook prototype

- fullstack-cert/python-projects/hash-table-lab/main.py
- fullstack-cert/python-projects/hash-table-lab/user-stories.md
> chore: add hash table prototype

- fullstack-cert/react-projects/usememo-currency-converter/index.html
- fullstack-cert/react-projects/usememo-currency-converter/index.jsx
- fullstack-cert/react-projects/usememo-currency-converter/styles.css
- fullstack-cert/react-projects/usememo-currency-converter/userstories.md
> chore(curriculum): add prototype for useMemo lab

- fullstack-cert/react-projects/live-search/index.html
- fullstack-cert/react-projects/live-search/index.jsx
- fullstack-cert/react-projects/live-search/styles.css
> feat: add React useEffect Hook prototype

- fullstack-cert/react-projects/search-app/index.html
- fullstack-cert/react-projects/search-app/index.jsx
- fullstack-cert/react-projects/search-app/notes.md
- fullstack-cert/react-projects/search-app/styles.css
Checklist:
Addresses https://github.com/freeCodeCamp/CurriculumExpansion/issues/554
This adds a simple search app project for the `useMemo` and `useCallback` workshop. If anyone can think of a better name, just let me know and I can update the code to match.
> feat: add use memo and use callback workshop

- fullstack-cert/react-projects/usememo-currency-converter/index.html
- fullstack-cert/react-projects/usememo-currency-converter/index.jsx
- fullstack-cert/react-projects/usememo-currency-converter/styles.css
This updates the styles to match our [style guide](https://design-style-guide.freecodecamp.org/).
Also, the form was updated to be slightly more complex and i11y-friendly.
> refactor: adjust lab-currency-converter with fcc styles and form

- fullstack-cert/python-projects/ceasar-cipher-workshop/main.py
> refactor: remove loop from cipher prototype

- fullstack-cert/python-projects/quick-sort-lab/main.py
- fullstack-cert/python-projects/quick-sort-lab/user-stories.md
> chore: add quick sort Python prototype 

- fullstack-cert/python-projects/selection-sort/main.py
- fullstack-cert/python-projects/selection-sort/user-stories.md
> feat: adding selection sort lab

- fullstack-cert/python-projects/binary-search-workshop/main.py
- fullstack-cert/python-projects/binary-search-workshop/notes-for-steps.md
> feat: adding binary search workshop

- fullstack-cert/js-projects/emoji-reactor/index.html
- fullstack-cert/js-projects/emoji-reactor/script.js
- fullstack-cert/js-projects/emoji-reactor/styles.css
> feat: add `querySelectorAll` workshop prototype

- fullstack-cert/python-projects/luhn-algo-lab/main.py
- fullstack-cert/python-projects/luhn-algo-lab/user-stories.md
> chore: convert luhn algorithm project to lab

- fullstack-cert/python-projects/salary-tracker-workshop/main.py
> feat: salary tracker workshop prototype

- fullstack-cert/python-projects/shortest-path-workshop/main.py
> feat : add shortest path algorithm workshop

- fullstack-cert/html-projects/table-accessibity-workshop/index.html
> feat: add table accessibility workshop

- fullstack-cert/python-projects/game-character-stats/main.py
- fullstack-cert/python-projects/game-character-stats/user-stories.md
> chore(curriculum): game character stats lab prototype

- fullstack-cert/python-projects/bisection-method-lab/main.py
- fullstack-cert/python-projects/bisection-method-lab/user-stories.md
> chore: add bisection method prototype and user stories

- fullstack-cert/python-projects/workshop-media-catalogue/main.py
> feat: add media catalogue workshop prototype

- fullstack-cert/css-projects/feature-selection/index.html
- fullstack-cert/css-projects/feature-selection/styles.css
- fullstack-cert/css-projects/feature-selection/user-stories.md
> feature selection for chekbox lab project

- fullstack-cert/css-projects/colored-boxes-layout/index.html
- fullstack-cert/css-projects/colored-boxes-layout/styles.css
> feat: add second flexbox workshop prototype

- fullstack-cert/python-projects/nth-fibonacci-number/main.py
- fullstack-cert/python-projects/nth-fibonacci-number/user-stories.md
> feat(curriculum): add python fibonacci lab

- fullstack-cert/typescript-projects/flashcard-quiz-app/package.json
- fullstack-cert/typescript-projects/flashcard-quiz-app/src/script.ts
Checklist:
Closes #XXXXX
There were 2 card interfaces in the app. Now there's only one.
> chore: remove duplicated interface

- fullstack-cert/d3-projects/sample.md
> feat: add d3 projects folder

- fullstack-cert/python-projects/classes-and-objects/main.py
- fullstack-cert/python-projects/classes-and-objects/user-stories.md
> chore: added prototype for classes and objects lab
